version: '3.9'

services:
  app:
    image: test-env/golang:0.1
    container_name: test-env-golang
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/app-backend:/go/src/app-backend/
    tty: true
    depends_on:
      - database
    ports:
      - 30000:3000

  database:
      image: test-env/postgres:0.1
      container_name: test-env-postgres
      build:
        context: .
        dockerfile: ./database/Dockerfile
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres-pass
      ports:
        - 5432:5432